apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: prod-youcube
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: youcube:dev
        imagePullPolicy: Never
        command: ["/bin/sh", "-c", "cd backend && celery -A tasks worker --loglevel=info --concurrency=4"]
        env:
        - name: ENV
          value: "prod"
        envFrom:
        - configMapRef:
            name: youcube-config
        resources:
          requests:
            memory: "512Mi" 
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"